services:
  - type: web
    name: research-agent
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: GROQ_MODEL_RRL
        value: llama-3.1-70b-versatile
      - key: GEMINI_API_KEY
        sync: false
      - key: SCOPUS_API_KEY
        sync: false
      - key: SPRINGER_API_KEY
        sync: false
      - key: CORE_API_KEY
        sync: false
      - key: UNPAYWALL_EMAIL
        sync: false
    staticPublishPath: frontend
